### ISSUE TITLE
Where do I place the configuration file, and what do i call it?

### ISSUE THREAD

**Issue by DrBeak1** [NicosKaralis/pushmeup#19]
I saw this question:
https://github.com/NicosKaralis/pushmeup/issues/7

But even that didn't explain clearly where i place the configuration information. Where do I configure all the needed info?

**Comment by NicosKaralis** [comment]
sorry for the delay.

The config should be put anywhere that is called before you actually need to call methods from this gem, you could configure it right before you send a notification.

But since the config need to be set only one time it is, usually, set on a initializer that is called once when the app starts, they are located at:

```
(rails app root)/config/initializers/
```
