### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate unknown

### ISSUE THREAD

**Issue by daniramdani** [NicosKaralis/pushmeup#26]
Hi Nicos,
After setup APNS configuration then running the code,  I got error :

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate unknown.

Do you any idea with this ?

Ruby : 2.1.1p76
Rails : 4.0.0

Best Regards,

**Comment by NicosKaralis** [comment]
no idea, does this error happen often? are your server behind a proxy?

From what i have searcher over the internet this error happens when your machine can't verify the root certificate for ssl, check this questions on SO: [this](http://stackoverflow.com/questions/19463827/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat) and [this](http://stackoverflow.com/questions/18321740/rails-4-and-ruby-2-net-http-ssl-request-opensslsslsslerror-ssl-connect-ret)

if you still can't get over this error, put in here the full trace of the error and the params you are trying to send (no certs, just variables and such)

**Comment by daniramdani** [comment]
Hi Nicos,

Thanks for your response, I'm still setup in my laptop/ local (develop), not behind proxy.

Here is what I'm trying to send :

APNS.pem = '/Users/cumungud/Documents/cert.pem'
APNS.pass = '12345'
device_token = '123abc456def'
APNS.send_notification(device_token, 'Hello iPhone!' )

then produce this :
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate unknown

Stack almost whole day :(

Thanks

**Comment by kunalkushwah** [comment]
When i try to send GCM notifications to the android devices, this same error occurs. What is the solution?

**Comment by NicosKaralis** [comment]
I couldn't find why this error happens, i believe it is something on the ssl layer that causes this, can you check date and time and recheck the pem file generated?

**Comment by kunalkushwah** [comment]
I got this error removed. Now when I send the notification (to a single GCM android device), it returns the Error 500. Does it happen often? I know this is a Google internal server error. Am i making a mistake in the following notification creation?
destination= Array.new
destination << #GCM_ID_here
data = {:subject => "hehahahaha", :text => "lololololol"}
GCM.send_notification( destination, data )

**Comment by NicosKaralis** [comment]
@kunalkushwah The response returned from `GCM.send_notification` is a `JSON` object, can you post the response here? and if it raises an error, could you post the full backtrace of that error?

**Comment by kunalkushwah** [comment]
@NicosKaralis Sir thanks for this beautiful gem. I have implemented all the required features. It was committing some minor errors which I sorted out. Cheers!

**Comment by NicosKaralis** [comment]
glad to hear everything is fine.
^^
